<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EventHouse.ShareKernel\EventHouse.ShareKernel.csproj" />
    <ProjectReference Include="..\..\src\EventHouse.Management.Domain\EventHouse.Management.Domain.csproj" />
    <ProjectReference Include="..\..\src\EventHouse.Management.Application\EventHouse.Management.Application.csproj" />
    <ProjectReference Include="..\..\src\EventHouse.Management.Infrastructure\EventHouse.Management.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\EventHouse.Management.Api\EventHouse.Management.Api.csproj" />
  </ItemGroup>

</Project>
