// <auto-generated />
using System;
using System.Collections.Generic;
using EventHouse.Management.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventHouse.Management.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ManagementDbContext))]
    [Migration("20260807034128_updateTimeZoneIdInEventVenueCalendar")]
    partial class updateTimeZoneIdInEventVenueCalendar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_artists");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Artists_Name");

                    b.ToTable("Artists", null, t =>
                        {
                            t.HasCheckConstraint("CK_Artist_Name_NotEmpty", "TRIM(name) <> ''");
                        });
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.ArtistGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_artist_genres");

                    b.HasIndex("ArtistId")
                        .IsUnique()
                        .HasDatabaseName("ux_artist_genres_artist_primary")
                        .HasFilter("is_primary = true");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_artist_genres_genre_id");

                    b.HasIndex("ArtistId", "GenreId")
                        .IsUnique()
                        .HasDatabaseName("UX_ArtistGenres_Artist_Genre");

                    b.ToTable("ArtistGenres", null, t =>
                        {
                            t.HasCheckConstraint("CK_ArtistGenre_ArtistId_NotEmpty", "artist_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_ArtistGenre_GenreId_NotEmpty", "genre_id <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.ArtistPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<Guid>("EventVenueCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_venue_calendar_id");

                    b.Property<bool>("IsHeadliner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_headliner");

                    b.Property<DateTime?>("SetEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("set_end");

                    b.Property<DateTime?>("SetStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("set_start");

                    b.HasKey("Id")
                        .HasName("pk_artist_performances");

                    b.HasIndex("EventVenueCalendarId")
                        .IsUnique()
                        .HasDatabaseName("UX_ArtistPerformances_OneHeadlinerPerCalendar")
                        .HasFilter("is_headliner = true");

                    b.HasIndex("ArtistId", "EventVenueCalendarId")
                        .IsUnique()
                        .HasDatabaseName("UX_ArtistPerformances_Artist_EventVenueCalendar");

                    b.ToTable("ArtistPerformances", null, t =>
                        {
                            t.HasCheckConstraint("CK_ArtistPerformance_ArtistId_NotEmpty", "artist_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_ArtistPerformance_EventVenueCalendarId_NotEmpty", "event_venue_calendar_id <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<byte>("Scope")
                        .HasColumnType("smallint")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Event_Name");

                    b.ToTable("Events", null, t =>
                        {
                            t.HasCheckConstraint("CK_Event_Name_NotEmpty", "TRIM(name) <> ''");

                            t.HasCheckConstraint("CK_Event_Scope_Range", "Scope IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.EventVenue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_event_venues");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_event_venues_venue_id");

                    b.HasIndex("EventId", "VenueId")
                        .IsUnique()
                        .HasDatabaseName("UX_EventVenues_Event_Venue");

                    b.ToTable("EventVenues", null, t =>
                        {
                            t.HasCheckConstraint("CK_EventVenue_EventId_NotEmpty", "event_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_EventVenue_VenueId_NotEmpty", "venue_id <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.EventVenueCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("EventVenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_venue_id");

                    b.Property<Guid>("SeatingMapId")
                        .HasColumnType("uuid")
                        .HasColumnName("seating_map_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.ComplexProperty<Dictionary<string, object>>("TimeZoneId", "EventHouse.Management.Domain.Entities.EventVenueCalendar.TimeZoneId#TimeZoneId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("time_zone_id");
                        });

                    b.HasKey("Id")
                        .HasName("pk_event_venue_calendars");

                    b.HasIndex("SeatingMapId")
                        .HasDatabaseName("ix_event_venue_calendars_seating_map_id");

                    b.HasIndex("EventVenueId", "StartDate")
                        .HasDatabaseName("ix_event_venue_calendars_event_venue_id_start_date");

                    b.HasIndex("EventVenueId", "StartDate", "EndDate")
                        .HasDatabaseName("IX_EventVenueCalendar_Overlap_Search");

                    b.ToTable("EventVenueCalendars", null, t =>
                        {
                            t.HasCheckConstraint("CK_EventVenueCalendar_EndDate", "(end_date IS NULL OR end_date >= start_date)");
                        });
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Genres_Name");

                    b.ToTable("Genres", null, t =>
                        {
                            t.HasCheckConstraint("CK_Genre_Name_NotEmpty", "TRIM(name) <> ''");
                        });
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.SeatingMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_seating_maps");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_seating_maps_venue_id");

                    b.HasIndex("VenueId", "Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_SeatingMap_Venue_Name_Version");

                    b.ToTable("SeatingMaps", null, t =>
                        {
                            t.HasCheckConstraint("CK_SeatingMap_VenueId_NotEmpty", "venue_id <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.ComplexProperty<Dictionary<string, object>>("Coordinates", "EventHouse.Management.Domain.Entities.Venue.Coordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("latitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("longitude");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TimeZoneId", "EventHouse.Management.Domain.Entities.Venue.TimeZoneId#TimeZoneId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("time_zone_id");
                        });

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Venues_Name");

                    b.HasIndex("CountryCode", "City")
                        .HasDatabaseName("ix_venues_country_code_city");

                    b.ToTable("Venues", (string)null);
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.ArtistGenre", b =>
                {
                    b.HasOne("EventHouse.Management.Domain.Entities.Artist", null)
                        .WithMany("Genres")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_genres_artists_artist_id");

                    b.HasOne("EventHouse.Management.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_artist_genres_genres_genre_id");
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.ArtistPerformance", b =>
                {
                    b.HasOne("EventHouse.Management.Domain.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_performances_artists_artist_id");

                    b.HasOne("EventHouse.Management.Domain.Entities.EventVenueCalendar", "EventVenueCalendar")
                        .WithMany("Performances")
                        .HasForeignKey("EventVenueCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_performances_event_venue_calendars_event_venue_calend");

                    b.Navigation("EventVenueCalendar");
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.EventVenue", b =>
                {
                    b.HasOne("EventHouse.Management.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_venues_events_event_id");

                    b.HasOne("EventHouse.Management.Domain.Entities.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_venues_venues_venue_id");

                    b.Navigation("Event");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.EventVenueCalendar", b =>
                {
                    b.HasOne("EventHouse.Management.Domain.Entities.EventVenue", "EventVenue")
                        .WithMany()
                        .HasForeignKey("EventVenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_venue_calendars_event_venues_event_venue_id");

                    b.HasOne("EventHouse.Management.Domain.Entities.SeatingMap", null)
                        .WithMany()
                        .HasForeignKey("SeatingMapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_venue_calendars_seating_maps_seating_map_id");

                    b.Navigation("EventVenue");
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.SeatingMap", b =>
                {
                    b.HasOne("EventHouse.Management.Domain.Entities.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seating_maps_venues_venue_id");
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.Artist", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("EventHouse.Management.Domain.Entities.EventVenueCalendar", b =>
                {
                    b.Navigation("Performances");
                });
#pragma warning restore 612, 618
        }
    }
}
