<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EventHouse.Management.Application\EventHouse.Management.Application.csproj" />
    <ProjectReference Include="..\EventHouse.Management.Domain\EventHouse.Management.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CoreSystem.Cache.Redis" />
    <PackageReference Include="CoreSystem.Idempotency.PostgreSql" />
    <PackageReference Include="CoreSystem.Idempotency.Redis" />
    <PackageReference Include="CoreSystem.Observability" />
    <PackageReference Include="CoreSystem.Resilience" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    
    <PackageReference Include="Scrutor" />
  </ItemGroup>

  <ItemGroup>
  	<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
		<_Parameter1>EventHouse.Management.Infrastructure.Tests</_Parameter1>
	</AssemblyAttribute>
  </ItemGroup>
  
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
